# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: name_gender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11name_gender.proto\"j\n\x14\x46irstNameGenderCount\x12\x14\n\x0c\x63ountry_code\x18\x01 \x01(\t\x12\x12\n\nfirst_name\x18\x02 \x01(\t\x12\x12\n\nmale_count\x18\x03 \x01(\x05\x12\x14\n\x0c\x66\x65male_count\x18\x04 \x01(\x05\x62\x06proto3')



_FIRSTNAMEGENDERCOUNT = DESCRIPTOR.message_types_by_name['FirstNameGenderCount']
FirstNameGenderCount = _reflection.GeneratedProtocolMessageType('FirstNameGenderCount', (_message.Message,), {
  'DESCRIPTOR' : _FIRSTNAMEGENDERCOUNT,
  '__module__' : 'name_gender_pb2'
  # @@protoc_insertion_point(class_scope:FirstNameGenderCount)
  })
_sym_db.RegisterMessage(FirstNameGenderCount)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FIRSTNAMEGENDERCOUNT._serialized_start=21
  _FIRSTNAMEGENDERCOUNT._serialized_end=127
# @@protoc_insertion_point(module_scope)
